config/routes.rb
Rails.application.routes.draw do
  # get 'homes/index'
  # get 'homes/show'
  # get 'homes/about'
  # devise_for :views
  # get 'comments/index'
  # get 'comments/show'
  # get 'comments/edit'
  # get 'posts/index'
  # get 'posts/show'
  # get 'posts/edit'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :posts
  end
  
  resources :posts do
    resources :comments
  end

  root 'posts#home'

  get '/home' => 'posts#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
 
 end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = current_user.posts.comments
  end

  def show
  end

  def new 
    @comment = Comment.new
    # render partial: "form"
  end

  def create 
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]
    if @comment.save!
      redirect_to post_path(@post)
    else  
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update 
    if @comment.update(comment_params)
      redirect_to comments_path
    else 
      render :edit
    end
  end

  def destroy 
    @comment.destroy 
    redirect_to post_path(@post)
  end

  private 
    def set_post 
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params 
      params.require(:comment).permit(:body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update]
  def index
    @posts = current_user.posts
  end

  def home
    @all_posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new 
    @post = Post.new
    render partial: "form"
  end

  def create 
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update 
    if @post.update(post_params)
      redirect_to posts_path
    else 
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id]) 
    if current_user.id == @post.user_id
      set_post
      @post.destroy 
      redirect_to posts_path
    else
      flash[:alert] = "Error, you don't have permission to delete this post"
      # redirect_to root_path
    end
  end

  private 
    def set_post 
      @post = current_user.posts.find(params[:id])
    end

    def post_params 
      params.require(:post).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
<div class="input-field col s6">
  <%= f.label :body %>
  <%= f.text_area :body %>
 </div>
 <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<%= render "form" %>

app/views/comments/show.html.erb
<%= @comment.body %>

<%= link_to "Delete Comment", [@post, @comment], method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Faceblock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
      <footer style="margin-top:25%;">
        <%= button_to "log out", destroy_user_session_path, method: :delete %>
      </footer>
    </div>
  </body>

  
</html>

app/views/posts/_form.html.erb
<div class="form-class">
  <h1 class="form-h1"><%= @post.id ? "Edit Post" : "Create Post" %></h1>

  <%= form_for [@post] do |f| %>
  <div class="input-field col s6">
  <%= f.label :body %>
  <%= f.text_area :body %>
  </div>
  <%= f.submit %>
  <% end %>
  </div>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/home.html.erb
<h1>ALL POSTS</h1>
<br/>
<%= link_to "Add New Post", new_post_path %>
<br/>
<% @all_posts.each do |post| %>
  <%= link_to "#{post.body}", post_path(post.id) %>
  <br/>
<% end %>

app/views/posts/index.html.erb
<h1><%= "#{current_user.first_name}'s POSTS" %></h1>
<br/>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= link_to "Post: #{post.body}", post_path(post.id) %>
        <%= " || "%>
        <%= link_to "Edit Post", edit_post_path(post.id) %>
        <br/>
      </li>
    <% end %>
  </ul>

<%= link_to 'Add New Post', new_post_path %>

app/views/posts/show.html.erb
<h1>POST</h1>
<%= @post.body %>
<%= " || "%>
<%= link_to "Delete Post", @post, method: :delete %>

<br/>
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
  <%= link_to "#{comment.body}", post_comment_path(@post, comment.id) %>
  <br/>
<% end %>
<%= link_to "Add Comment", new_post_comment_path(@post) %>

<%# <%= @post.comments %> 